export const programming_skills = [
	'.NET',
	'ABAP',
	'ADO.NET',
	'AI Programming',
	'ALGOL',
	'APL',
	'ASCII Encoding',
	'ASP / ASP.NET',
	'ActionScript',
	'Ada',
	'Alice',
	'Assembly Language',
	'Awk',
	'BBC Basic',
	'Backbone.js',
	'Books',
	'Bootstrap',
	'C',
	'C#',
	'C++',
	'CGI',
	'COBOL',
	'CORBA',
	'CSS',
	'CVS',
	'CakePHP',
	'Chyrp',
	'Cocoa',
	'CodeIgniter',
	'Cookies',
	'D',
	'DOM',
	'Delphi',
	'Dreamweaver',
	'Drupal Coding Standards',
	'Elixir',
	'Erlang',
	'Extreme Programming',
	'F#',
	'FFmpeg',
	'FORTH',
	'FORTRAN',
	'Functional Programming',
	'GATE',
	'GNUstep',
	'Git',
	'Go',
	'HTML',
	'Haskell',
	'IDL',
	'INTERCAL',
	'ImageMagick',
	'JSON',
	'Java',
	'Javascript',
	'jQuery',
	'LabVIEW',
	'Laravel',
	'Linked Lists',
	'Linux Programming',
	'Lisp',
	'Logo',
	'MDN',
	'ML',
	'MPI',
	'MS Access',
	'MS-DOS',
	'MS-Windows',
	'MSXML',
	'Machine Learning',
	'Mandriva Linux',
	'MantisBT',
	'Mercurial',
	'MetaQuotes Language',
	'Modula-3',
	'MySQL',
	'NXT-G',
	'Ncurses',
	'NetCDF',
	'Network Programming',
	'Node.js',
	'OAuth',
	'OCaml',
	'OS Development',
	'Object-Oriented Programming',
	'Objective-C',
	'OpenCL',
	'OpenID',
	'OpenSSL',
	'PHP',
	'PHProjekt',
	'PL/I',
	'PL/SQL',
	'PROLOG',
	'Pascal',
	'Perl',
	'PostScript',
	'PostgreSQL',
	'Project Management',
	'Pure Data',
	'Python',
	'R',
	'RapidWeaver',
	'Raspberry Pi',
	'RavenDB',
	'React',
	'RegEx',
	'Rexx',
	'Robots',
	'Ruby on Rails',
	'S-PLUS',
	'SAS',
	'SGML',
	'SMIL',
	'SNOBOL',
	'SOAP',
	'SQL',
	'SQLite',
	'SSH',
	'SSI',
	'Scala',
	'Sed',
	'Simula',
	'Smalltalk',
	'Sorting Algorithms',
	'Stata',
	'Subversion',
	'Swift',
	'Tcl/Tk',
	'TeX and LaTeX',
	'UNIX Programming',
	'URL',
	'Ubuntu',
	'Umbraco',
	'Unified Modeling Language',
	'Unix Shells',
	'VHDL',
	'VRML',
	'Verilog',
	'Vi',
	'Visual Basic',
	'Visual FoxPro',
	'WAP/WML',
	'WCF',
	'WSDL',
	'WSGI',
	'Web Standards',
	'WebKit Web Inspector',
	'XML',
	'XSL',
	'Xaraya',
	'YUI',
	'Zikula',
];

export const hobbies_constants = [
	'Reading Books',
	'Writing Blogs',
	'Watching TV',
	'Listening to music',
	'Playing games',
	'Watching movies',
];

export const causes_constant = [
	'Children',
	'Animals',
	'Environment',
	'Human Rights',
	'Humanitarian',
];

export const education_degrees = [
	'High School',
	'Associate Degree',
	'Bachelor’s Degree',
	'Minor Degree',
	'Doctoral Degree',
];

export const sectors_constant = [
	'Accountancy, Banking and Finance ',
	'Business, Consulting and Management ',
	'Charity and Voluntary Work ',
	'Creative Arts and Design ',
	'Energy and Utilities ',
	'Engineering and Manufacturing ',
	'Environment and Agricultur ',
	'Healthcare ',
	'Hospitality and Events Management ',
	'Information Technology ',
	'Law ',
	'Law Enforcement and Security ',
	'Leisure, Sport and Tourism ',
	'Marketing, Advertising and PR ',
	'Media and Internet ',
	'Property and Construction ',
	'Public Services and Administration ',
	'Recruitment and HR ',
	'Retail ',
	'Sales ',
	'Science and Pharmaceuticals ',
	'Social Care ',
	'Teacher Training and Education',
	'Transport and Logistics',
];

export const employment_type_list = [
	'Full Time',
	'Part Time',
	'Contract',
	'Internship',
	'Freelance',
	'Self-Employed',
	'Seasonal',
	'Apprenticeship',
];

export const language_constant = {
	langs: [
		'English',
		'Turkish',
		'German',
		'Spanish',
		'French',
		'Chinese',
		'Russian',
		'Abkhaz',
		'Afar',
		'Afrikaans',
		'Akan',
		'Albanian',
		'Amharic',
		'Arabic',
		'Aragonese',
		'Armenian',
		'Assamese',
		'Avaric',
		'Avestan',
		'Aymara',
		'Azerbaijani',
		'Bambara',
		'Bashkir',
		'Basque',
		'Belarusian',
		'Bengali',
		'Bihari',
		'Bislama',
		'Bosnian',
		'Breton',
		'Bulgarian',
		'Burmese',
		'Catalan',
		'Chamorro',
		'Chechen',
		'Chichewa',
		'Chuvash',
		'Cornish',
		'Corsican',
		'Cree',
		'Croatian',
		'Czech',
		'Danish',
		'Divehi',
		'Dutch',
		'Dzongkha',
		'Esperanto',
		'Estonian',
		'Ewe',
		'Faroese',
		'Fijian',
		'Finnish',
		'Fula',
		'Galician',
		'Georgian',
		'Greek',
		'Guarana',
		'Gujarati',
		'Haitiane',
		'Hausa',
		'Hebrew',
		'Herero',
		'Hindi',
		'Hiri Motu',
		'Hungarian',
		'Interlingua',
		'Indonesian',
		'Interlingue',
		'Irish',
		'Igbo',
		'Inupiaq',
		'Ido',
		'Icelandic',
		'Italian',
		'Inuktitut',
		'Japanese',
		'Javanese',
		'Kalaallisut',
		'Kannada',
		'Kanuri',
		'Kashmiri',
		'Kazakh',
		'Khmer',
		'Kikuyu',
		'Kinyarwanda',
		'Kyrgyz',
		'Komi',
		'Kongo',
		'Korean',
		'Kurdish',
		'Kwanyama',
		'Latin',
		'Luxembourgish',
		'Ganda',
		'Limburgish',
		'Lingala',
		'Lao',
		'Lithuanian',
		'Luba-Katanga',
		'Latvian',
		'Manx',
		'Macedonian',
		'Malagasy',
		'Malay',
		'Malayalam',
		'Maltese',
		'Maori',
		'Marathi',
		'Marshallese',
		'Mongolian',
		'Nauru',
		'Navajo',
		'Norwegian Bokmal',
		'North Ndebele',
		'Nepali',
		'Ndonga',
		'Norwegian Nynorsk',
		'Norwegian',
		'Nuosu',
		'South Ndebele',
		'Occitan',
		'Ojibwe',
		'Old Slavonic',
		'Oromo',
		'Oriya',
		'Ossetian',
		'Panjabi',
		'Pali',
		'Persian (Farsi)',
		'Polish',
		'Pashto',
		'Portuguese',
		'Quechua',
		'Romansh',
		'Kirundi',
		'Romanian',
		'Sanskrit',
		'Sardinian',
		'Sindhi',
		'Northern Sami',
		'Samoan',
		'Sango',
		'Serbian',
		'Scottish Gaelic',
		'Shona',
		'Sinhala',
		'Slovak',
		'Slovene',
		'Somali',
		'Southern Sotho',
		'Sundanese',
		'Swahili',
		'Swati',
		'Swedish',
		'Tamil',
		'Telugu',
		'Tajik',
		'Thai',
		'Tigrinya',
		'Tibetan',
		'Turkmen',
		'Tagalog',
		'Tswana',
		'Tonga',
		'Tsonga',
		'Tatar',
		'Twi',
		'Tahitian',
		'Uyghur',
		'Ukrainian',
		'Urdu',
		'Uzbek',
		'Venda',
		'Vietnamese',
		'Volapuk',
		'Walloon',
		'Welsh',
		'Wolof',
		'Western Frisian',
		'Xhosa',
		'Yiddish',
		'Yoruba',
		'Zhuang',
		'Zulu',
	],
	proficiency: ['Beginner', 'Intermediate', 'Advanced', 'Native'],
};

export const job_list = [
	'.NET Developer',
	'ACCESSIBILITY SPECIALIST',
	'Admin Big Data',
	'AGILE PROJECT MANAGER',
	'Android Developer',
	'Ansible Automation Engineer',
	'Ansible Operations Engineer',
	'AppDynamics Engineer',
	'Application Security Engineer',
	'Artifactory Administrator',
	'Artifactory Engineer',
	'Artificial Intelligence (AI) / Machine Learning Engineer',
	'Artificial intelligence / Machine Learning Engineer',
	'Artificial Intelligence / Machine Learning Leader',
	'Artificial Intelligence / Machine Learning Sr.Leader',
	'Artificial intelligence Architect',
	'Artificial Intelligence Researcher',
	'Assignment Coordinator',
	'AWS DevOps Engineer',
	'AWS Solutions Architect',
	'Azure DevOps Engineer',
	'Bamboo Engineer',
	'Big Data Architect',
	'Big Data Engineer',
	'Big Data Specialist',
	'Bitbucket Engineer',
	'Blockchain Developer',
	'Build and Release Engineer',
	'Build Engineer',
	'Business Account Manager',
	'BUSINESS SYSTEMS ANALYST',
	'C# Developer',
	'Career Advisor',
	'Career Consultant',
	'Career Development Strategist',
	'CEO',
	'Chef InSpec Engineer',
	'Chef Operations Engineer',
	'Chief Architect',
	'Chief Human Resource Officer',
	'CIO/Chief Digital Officer/Chief Innovation Officer',
	'Cloud administrator',
	'Cloud architect',
	'Cloud automation engineer',
	'Cloud engineer',
	'Cloud network engineer',
	'Cloud Security Engineer',
	'CNC Programmer',
	'Coder',
	'COMPUTER GRAPHICS ANIMATOR',
	'Computer Hardware Engineer',
	'Computer Network Architect',
	'Computer Programmer',
	'Computer Research Scientist',
	'Computer Systems Analyst',
	'Confluence Engineer',
	'Consul Engineer',
	'CONTENT MANAGER',
	'CONTENT STRATEGIST',
	'Coverage.py Engineer',
	'CTO',
	'Data Analyst',
	'Data Architect',
	'Data Engineer',
	'DATA MODELER',
	'Data Scientist',
	'Database Administrator',
	'Datadog Engineer',
	'Developer',
	'DevOps Architect',
	'DevOps Engineer',
	'DEVOPS MANAGER',
	'DevSecOps Architect',
	'DevSecOps Engineer',
	'Digital Marketing Analyst',
	'Digital Marketing Manager',
	'Director of Engineering',
	'Docker Engineer',
	'ELK Engineer',
	'Embedded Software Engineer',
	'Engineering Manager',
	'Engineering Project Manager',
	'Engineering Project Manager/Engineering Manager',
	'Entry Level Developer',
	'Entry Level Network Engineer',
	'Entry Level Programmer',
	'Entry Level Software Developer',
	'Entry Level Software Engineer',
	'Entry Level Web Developer',
	'Envoy Engineer',
	'Falco Engineer',
	'FluentD Engineer',
	'Fortify Engineer',
	'FRAMEWORKS SPECIALIST',
	'Front End Developer',
	'Front End Web Developer',
	'FRONT-END DESIGNER',
	'FRONT-END DEVELOPER',
	'Full Stack Developer',
	'Full Stack JAVA Developer/Programmer/Engineer',
	'Full Stack Python Developer/Programmer/Engineer',
	'FULL-STACK DEVELOPER',
	'Game Developer',
	'GCP DevOps Engineer',
	'Gerrit Administrator',
	'Gerrit Engineer',
	'Git Engineer',
	'Github Engineer',
	'GitLab Engineer',
	'Gradle Engineer',
	'Grafana Engineer',
	'Groovy Engineer',
	'GROWTH HACKER',
	'HR Business Partner',
	'HR Coordinator',
	'HR Director',
	'HR Generalist',
	'HR Manager',
	'HR Specialist',
	'Human Resource Information Specialist',
	'Human Resources Officer',
	'INFORMATION ARCHITECT',
	'Information Security Analyst',
	'INTERACTION DESIGNER',
	'Intern Software Developer',
	'IOS Developer',
	'Istio Engineer',
	'IT Infra Manager',
	'IT Manager',
	'JaCoCO Engineer',
	'Java Developer',
	'JavaScript Developer',
	'Jenkins Engineer',
	'Jira Administrator',
	'JIRA Engineer',
	'Jr Developer',
	'Junior Developer',
	'Junior Front End Developer',
	'Junior IOS Developer',
	'Junior Software Developer',
	'Junior Software Engineer',
	'Junior Web Developer',
	'JUnit Engineer',
	'kubernetes Administrator',
	'Kubernetes Engineer',
	'Kubernetes Operations Engineer',
	'Learning and Development co-ordinators',
	'Learning and Development Manager',
	'Machine learning Architect',
	'Machine Learning Engineer',
	'MARKETING TECHNOLOGIST',
	'MAVEN Engineer',
	'Micro services / API Lead Designer',
	'MOBILE APP DEVELOPER',
	'Mobile Application Developer',
	'MOBILE DEVELOPER',
	'Mulesoft Developer',
	'Nagios Engineer',
	'Network and Systems Administrator',
	'Network Engineer',
	'New Grad Software Engineer',
	'New Relic Engineer',
	'Nexus Engineer',
	'Nomad Engineer',
	'Notary Engineer',
	'Octopus Deploy Engineer',
	'OpenShift Engineer',
	'OpenStack Engineer',
	'Operations Engineer',
	'Oracle Developer',
	'Oracle SQL Developer',
	'Packer Engineer',
	'Payroll Coordinator',
	'Personnel Agent',
	'PHP Developer',
	'Placement Coordinator',
	'Powershell Engineer',
	'Principal Software Engineer',
	'Principle Engineer in Artificial Intelligence',
	'Principle Engineer in Big Data',
	'Principle Engineer in Data Analysis',
	'Principle Engineer in Machine Learning',
	'Procurement manager',
	'Product Manager',
	'Production Support Engineer',
	'Programmer',
	'Programmer Analyst',
	'Project Manager',
	'Prometheus Engineer',
	'Puppet Engineer',
	'Puppet Operations Engineer',
	'PyTest Engineer',
	'Python Developer',
	'QA (QUALITY ASSURANCE) SPECIALIST',
	'QA Engineer',
	'React Developer',
	'Recruiter',
	'Recruiting Coordinator',
	'Recruiting Director',
	'Recruiting Manager',
	'Robotics Engineer',
	'RUBY ON RAILS DEVELOPER',
	'Salesforce Developer',
	'Search Engine Optimization',
	'SECURITY SPECIALIST',
	'Selenium Engineer',
	'Senior Ansible Development Engineer',
	'Senior Build and Release Engineer',
	'Senior Build Engineer',
	'Senior Cloud Architect',
	'Senior DevOps Architect',
	'Senior DevOps Engineer',
	'Senior DevSecOps Architect',
	'Senior DevSecOps Engineer',
	'Senior Manager IT',
	'Senior Site reliability Engineer',
	'Senior Software Engineer/Senior Software Developer',
	'Senior SRE Architect',
	'Senior SRE Engineer',
	'SEO CONSULTANT',
	'SEO Engineer',
	'SEO Manager',
	'Sharepoint Developer',
	'Site Reliability Engineer (Kubernetes – Docker)',
	'SOCIAL MEDIA MANAGER',
	'Social Media Marketing Analyst',
	'Social Media Marketing Manager',
	'Software Architect',
	'Software Developer',
	'SOFTWARE DEVELOPERS',
	'Software Engineer',
	'SonarQube Engineer',
	'Splunk Engineer',
	'Splunk Enterprise Security Engineer',
	'SQL Developer',
	'SRE Architect',
	'SRE Engineer',
	'SYSTEMS ADMINISTRATOR',
	'SYSTEMS ENGINEER',
	'TeamCity Engineer',
	'Tech Sales Engineer',
	'TECHNICAL ACCOUNT MANAGER',
	'TECHNICAL LEAD',
	'Technical Lead/Engineering Lead/Team Lead',
	'Technical Project Manager',
	'Terraform Engineer',
	'TFS Engineer',
	'Twistkock Engineer',
	'UDeploy Engineer',
	'UI DESIGNER',
	'UI Developer',
	'Unity Developer',
	'UX DESIGNER',
	'Vault Engineer',
	'VP of Engineering',
	'VP of Engineering/Director of Engineering',
	'VP of HR',
	'VP of Marketing',
	'VP of Product Management/Head of Product',
	'WEB ANALYTICS DEVELOPER',
	'Web Designer (UI/UX Designer)',
	'Web Developer',
	'WordPress Developer',
	'XL Deploy Engineer',
	'Zabbix Engineer',
];

export const currencies = {
	EUR: 'EUR',
	GBP: 'GBP',
	TRY: 'TL',
	USD: 'USD',
};

export const graduationDates = Array.from(Array(60).keys()).map((year) =>
	(year + 2015).toString()
);

export const entry_amounts = [10, 25, 50];

export const workplaceTypes = ['On Site', 'Hybrid', 'Remote'];

export const constantGradStatus = ['Employed', 'Self Employed', 'Unemployed'];

export const routesForReport = {
	admin: [
		'Dashboard',
		'Companies',
		'Alumni',
		'Alumni > Details',
		'Accounts',
		'Accounts > Details',
		'UP School Programs',
		'Other',
	],

	employee: [
		'T & C',
		'My Favourites',
		'Talent Marketplace',
		'Talent Marketplace > Profile',
		'Other',
	],

	student: [
		'Profile > General',
		'Profile > Programs',
		'Profile > Background',
		'Profile > Job Preferences',
		'Profile > Settings',
		'Other',
	],
};

// function draw() {
//   const canvas = document.getElementById('canvas-tutorial');
//   if (canvas.getContext) {
//     const ctx = canvas.getContext('2d');

//     // ctx.fillStyle = 'rgb(200, 0, 0)';
//     // ctx.fillRect(10, 10, 50, 50);

//     // ctx.fillStyle = 'rgba(0, 0, 200, 0.5)';
//     // ctx.fillRect(30, 30, 50, 50);

//     // ctx.beginPath();
//     // ctx.moveTo(75, 50);
//     // ctx.lineTo(100, 75);
//     // ctx.lineTo(100, 25);
//     // ctx.fill();

//     // ctx.beginPath();
//     // ctx.arc(75, 75, 50, 0, Math.PI * 2, true); // Outer circle
//     // ctx.moveTo(110, 75);
//     // ctx.arc(75, 75, 35, 0, Math.PI, false); // Mouth (clockwise)
//     // ctx.moveTo(65, 65);
//     // ctx.arc(60, 65, 5, 0, Math.PI * 2, true); // Left eye
//     // ctx.moveTo(95, 65);
//     // ctx.arc(90, 65, 5, 0, Math.PI * 2, true); // Right eye
//     // ctx.stroke();

//     // // Filled triangle
//     // ctx.beginPath();
//     // ctx.moveTo(25, 25);
//     // ctx.lineTo(105, 25);
//     // ctx.lineTo(25, 105);
//     // ctx.fill();

//     // // Stroked triangle
//     // ctx.beginPath();
//     // ctx.moveTo(125, 125);
//     // ctx.lineTo(125, 45);
//     // ctx.lineTo(45, 125);
//     // ctx.closePath();
//     // ctx.stroke();

//     // for (let i = 0; i < 4; i++) {
//     //   for (let j = 0; j < 3; j++) {
//     //     ctx.beginPath();
//     //     const x = 25 + j * 50; // x coordinate
//     //     const y = 25 + i * 50; // y coordinate
//     //     const radius = 20; // Arc radius
//     //     const startAngle = 0; // Starting point on circle
//     //     const endAngle = Math.PI + (Math.PI * j) / 2; // End point on circle
//     //     const counterclockwise = i % 2 !== 0; // clockwise or counterclockwise

//     //     ctx.arc(x, y, radius, startAngle, endAngle, counterclockwise);

//     //     if (i > 1) {
//     //       ctx.fill();
//     //     } else {
//     //       ctx.stroke();
//     //     }
//     //   }
//     // }

//     // Quadratic curves example
//     ctx.beginPath();
//     ctx.moveTo(75, 25);
//     ctx.quadraticCurveTo(25, 25, 25, 62.5);
//     ctx.quadraticCurveTo(25, 100, 50, 100);
//     ctx.quadraticCurveTo(50, 120, 30, 125);
//     ctx.quadraticCurveTo(60, 120, 65, 100);
//     ctx.quadraticCurveTo(125, 100, 125, 62.5);
//     ctx.quadraticCurveTo(125, 25, 75, 25);
//     ctx.stroke();

//     // Cubic curves example
//     ctx.beginPath();
//     ctx.moveTo(75, 40);
//     ctx.bezierCurveTo(75, 37, 70, 25, 50, 25);
//     ctx.bezierCurveTo(20, 25, 20, 62.5, 20, 62.5);
//     ctx.bezierCurveTo(20, 80, 40, 102, 75, 120);
//     ctx.bezierCurveTo(110, 102, 130, 80, 130, 62.5);
//     ctx.bezierCurveTo(130, 62.5, 130, 25, 100, 25);
//     ctx.bezierCurveTo(85, 25, 75, 37, 75, 40);
//     ctx.fill();

//     const rectangle = new Path2D();
//     rectangle.rect(10, 10, 50, 50);

//     const circle = new Path2D();
//     circle.arc(100, 35, 25, 0, 2 * Math.PI);

//     ctx.stroke(rectangle);
//     ctx.fill(circle);
//   }
// }

// <section className='h-[500px] flex justify-center items-center border-double border-neutral-500'>
//   <canvas
//     id='canvas-tutorial'
//     width='400'
//     height='400'
//     className='bg-white border-solid border-fuchsia-900'
//   >
//     Eyo
//   </canvas>
// </section>;
