const data = {
  bayiler: [
    {
      name: 'Fatih Bayi',
    },
    {
      name: '4. Levent Bayi',
    },
    {
      name: 'Çekmeköy Bayi',
    },
    {
      name: 'Pendik Bayi',
    },
  ],
  products: [
    {
      name: 'Basic Shirt',
      category: 'Shirts',
      category_id: '5',
      image: '/images/shirt1.jpg',
      price: 69.0,
      brand: 'Nike',
      rating: 2.3,
      numReviews: 20,
      countInStock: 10,
      description: 'A popular shirt',
    },
    {
      name: 'Fit Shirt',
      category: 'Shirts',
      category_id: '5',
      image: '/images/shirt2.jpg',
      price: 169.0,
      brand: 'Under Armour',
      rating: 4.1,
      numReviews: 5,
      countInStock: 3,
      description: 'A not so popular shirt',
    },
    {
      name: 'Loose Shirt',
      category: 'Shirts',
      category_id: '5',
      image: '/images/shirt3.jpg',
      price: 19.99,
      brand: 'Decathlon',
      rating: 4.8,
      numReviews: 57,
      countInStock: 57,
      description: 'A popular shirt',
    },
    {
      name: 'Basic Pants',
      category: 'Pants',
      category_id: '5',
      image: '/images/pants1.jpg',
      price: 70,
      brand: 'Koton',
      rating: 4.5,
      numReviews: 9,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'Slim Jeans',
      category: 'Pants',
      category_id: '5',
      image: '/images/pants2.jpg',
      price: 70,
      brand: 'LC Waikiki',
      rating: 2.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular jeans',
    },
    {
      name: 'Dirty Jeans',
      category: 'Pants',
      category_id: '5',
      image: '/images/pants3.jpg',
      price: 70,
      brand: 'Koton',
      rating: 3.5,
      numReviews: 13,
      countInStock: 21,
      description: 'A good choice for jeans',
    },
  ],
};

export default data;
